{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}
package:
    name: ts-weatherforecast
    version: {{ version }}

source:
    path: ../

build:
    noarch: python
    entry_points:
      - run_weatherforecast = lsst.ts.weatherforecast:execute_csc
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
    requires:
        - ts-conda-build =0.4
        - ts-idl {{ idl_version }}
        - ts-salobj {{ salobj_version }}
    source_files:
        - python
        - tests
        - pyproject.toml
    commands:
        - pytest

requirements:
    host:
        - python {{ python }}
        - pip
        - setuptools_scm
        - setuptools
    build:
        - python {{ python }}
        - setuptools_scm
        - setuptools
    run:
        - python {{ python }}
        - ts-salobj
        - ts-idl
        - aiohttp >=3.8
